### ISSUE TITLE
Questions before using this

### ISSUE THREAD

**Issue by oxysoft** [dario-zubovic/metaballs#1]
First off, let me say that this looks absolutely awesome. I wanted to use metaballs in my game a couple of months ago but could not because honestly the complexity and mathematics used here go far over my head. I had to resort to looking online but all I could found was the horrible metaballs monobehaviour script on the Unity community wikis. It worked but it was all done on the CPU and, by association, was very inefficient. It also had some severe restrictions in that the metaballs seemed to be bound within a single box, and all of the metaballs themselves had to be managed by that single script; You could not just add a single metaball at the start of the game, then later add another far back and gradually move it over and see them connect. 

Before I use these, I'd like to know
- Does it have any of the restrictions above, or anything else I should know about?
- I am understanding that this runs on the GPU, but how are the performances looking on this? The game I'm making is fairly low poly so I won't have the resolution very high. How many metaballs can I expect to be able to move around before it becomes a problem on an average computer? I will use it mainly for particle effects and stuff like that, where each ball will not have a very long lifespan. It will not run on mobile devices also, so this is out of the equation.
- Could there be compatibility issues with older cards or will it run on most computers nowadays?
- Can I use this in a commercial game without any licensing or legal fears. (I would however tip you some money if the game generated any revenue at all, for letting me use this great asset)

Thanks

**Comment by AugustYadon** [comment]
Late comment, because I just found this while trying to make a "water balloon throwing" mechanic in my VR game. To answer your last question, if you read the license file, he grants permission for commercial use. You just have to acknowledge the author/programmer.

**Comment by dario-zubovic** [comment]
Hi! No idea how I missed this.
- Yes, metaballs are still bound withing single box. However, since it's run on GPU, you're free to increase size of a box with a smaller performance hit.
- GPU needs to support compute shaders, so older cards might be having some problems.
- You are free to use code in any way you see fit - under MIT license.
Anyway, I have never gotten around to finishing this. Check out fork by @arodic who has made some progress: https://github.com/arodic/metaballs
